# -*- mode: ruby -*-
# vi: set ft=ruby :

$insallDocker = <<SCRIPT
cd $HOME
mkdir app
apk update && apk add docker docker-compose
rc-update add docker
SCRIPT
Vagrant.configure("2") do |config|
  
  config.vm.define "manager01" do |manager01|
    manager01.vm.hostname = "manager"
    manager01.vm.box = "generic/alpine318"
    manager01.vm.synced_folder ".", "/vagrant"
    manager01.vm.provision "shell", inline: $insallDocker
    manager01.vm.provision "file", source: "./docker-compose.yml", destination: "$HOME/app/docker-compose.yml"
    manager01.vm.provision "file", source: "./portainer-agent-stack.yml", destination: "$HOME/app/portainer-agent-stack.yml"
    manager01.vm.provision "file", source: "./managerScript.sh", destination: "$HOME/app/managerScript.sh"
    manager01.vm.network "private_network", ip: "192.168.56.0"
    manager01.vm.network "forwarded_port", guest: 9000, host: 9000, auto_correct: true
    manager01.vm.network "forwarded_port", guest: 8081, host: 8081, auto_correct: true
    manager01.vm.network "forwarded_port", guest: 8082, host: 8082, auto_correct: true
    manager01.vm.network "forwarded_port", guest: 8083, host: 8083, auto_correct: true
    manager01.vm.network "forwarded_port", guest: 8084, host: 8084, auto_correct: true
    manager01.vm.network "forwarded_port", guest: 8085, host: 8085, auto_correct: true
    manager01.vm.network "forwarded_port", guest: 8086, host: 8086, auto_correct: true
    manager01.vm.network "forwarded_port", guest: 8087, host: 8087, auto_correct: true
    manager01.vm.provider "virtualbox" do |vb|
      vb.memory = "2000"
    end
  end

  config.vm.define "worker01" do |worker01|
   worker01.vm.hostname = "worker01"
    worker01.vm.box = "generic/alpine318"
    worker01.vm.synced_folder ".", "/vagrant"
    worker01.vm.provision "shell", inline: $insallDocker
    worker01.vm.provision "file", source: "./workerScript.sh", destination: "$HOME/app/workerScript.sh"
    worker01.vm.network "private_network", ip: "192.168.56.1"
    worker01.vm.provider "virtualbox" do |vb|
     vb.memory = "1500"
    end
  end

  config.vm.define "worker02" do |worker02|
    worker02.vm.hostname = "worker02"
    worker02.vm.box = "generic/alpine318"
    worker02.vm.synced_folder ".", "/vagrant"
    worker02.vm.provision "shell", inline: $insallDocker
    worker02.vm.provision "file", source: "./workerScript.sh", destination: "$HOME/app/workerScript.sh"
    worker02.vm.network "private_network", ip: "192.168.56.2"
    worker02.vm.provider "virtualbox" do |vb|
      vb.memory = "1500"
    end
  end
end
